### ISSUE TITLE
Amazon->ion->utils.py

### ISSUE THREAD

**Issue by omid29sarei** [amazon-ion/ion-python#241]
I have been using this in conjunction with pyqldb and noticed some unexpected behavior when it comes to handling the _EnumMetaClass and Enum and start to dig into this and noticed from version  0.9.3 that those 2 classes are removed from the utils.py within amazon ion and this cause an expected **ImportError: cannot import name 'Enum' from 'amazon.ion.util'**

Based on the documentation provided here : [Ion-Python](https://ion-python.readthedocs.io/en/latest/_modules/amazon/ion/util.html)
This should be the correct structure of the file but those 2 classes are missing

**Comment by omid29sarei** [comment]
```
 Python 2/3 compatibility
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import six
import sys

from collections import namedtuple


class _EnumMetaClass(type):
    """Metaclass for simple enumerations.

    Specifically provides the machinery necessary to emulate simplified Python 3.4 enumerations.
    """
    def __init__(cls, name, bases, attrs):
        members = {}
        # Re-bind any non magic-named method with an instance of the enumeration.
        for attr_name, attr_value in six.iteritems(attrs):
            if not attr_name.startswith('_') and not callable(attr_value) and not isinstance(attr_value, property):
                if not isinstance(attr_value, int):
                    raise TypeError('Enum value must be an int: %r' % attr_value)
                actual_value = cls(attr_name, attr_value)
                setattr(cls, attr_name, actual_value)
                members[attr_value] = actual_value

        # Store the members reverse index.
        cls._enum_members = members

        type.__init__(cls, name, bases, attrs)

    def __getitem__(cls, name):
        """Looks up an enumeration value field by integer value."""
        return cls._enum_members[name]

    def __iter__(self):
        """Iterates through the values of the enumeration in no specific order."""
        return six.itervalues(self._enum_members)


@six.add_metaclass(_EnumMetaClass)
class Enum(int):
    """Simple integer based enumeration type.

    Examples:
        The typical declaration looks like::

            class MyEnum(Enum):
                A = 1
                B = 2
                C = 3

        At this point ``MyEnum.A`` is an instance of ``MyEnum``.

    Note:
        Proper enumerations were added in Python 3.4 (PEP 435), this is a very simplified implementation
        based loosely on that specification.

        In particular, implicit order of the values is not supported.

    Args:
        value (int): the value associated with the enumeration.

    Attributes:
        name (str): The name of the enum.
        value (int): The original value associated with the enum.
    """
    _enum_members = {}

    def __new__(cls, name, value):
        return int.__new__(cls, value)

    def __init__(self, name, value):
        self.name = name
        self.value = value
    
    def __getnewargs__(self):
        return (self.name, self.value)

    def __str__(self):
        return '<%s.%s: %s>' % (type(self).__name__, self.name, self.value)
    __repr__ = __str__
```

This code should be added to the file. I have tried to create a PR but i was not allowed to create a PR, Otherwise would do that for you

**Comment by cheqianh** [comment]
Thanks for letting us know, I'll look into this class and get back to you once I have updates.

**Comment by omid29sarei** [comment]
My pleasure, Hope it was helpful
Regards,
Omid

**Comment by cheqianh** [comment]
> ImportError: cannot import name 'Enum' from 'amazon.ion.util'

Is there any specific code example you are using that imports `amazon.ion.util.Enum`?

In addition, which python version are you using? The latest ion-python does not use `six` module anymore.

**Comment by cheqianh** [comment]
> you also dropped those 2 meta classes where there were references of that from other packages.

The library uses `IntEnum` instead of `amazon.ion.util.Enum` now (E.g, in [amazon/ion/core.py](https://github.com/amazon-ion/ion-python/blob/master/amazon/ion/core.py#L16)). Is there any specific place that throws `ImportError: cannot import name 'Enum' from 'amazon.ion.util'` within the library?

> You can also have a look at your official documentation [here](https://ion-python.readthedocs.io/en/latest/_modules/amazon/ion/util.html)

Thank you for catching up this. The documentation is out-of-date, let me see how I can enable it.

**Comment by NVivith** [comment]
I am facing the same issue as well, do we have any alternative approach to overcome this

**Comment by omid29sarei** [comment]
Yes, i downgrade it and it worked perfectly. Obv depending on what packages
are calling it you might find different version that you need to role back.
FYI - I mentioned the version that I rolled back to at the beginning of
this thread

**Comment by cheqianh** [comment]
https://github.com/amazon-ion/ion-python/pull/246 adds the enum class back, which should solve the issue you guys have. I also marked the class as **deprecation**.

**Comment by cheqianh** [comment]
https://github.com/amazon-ion/ion-python/pull/246 adds the enum class back, which should solve the import issue. I marked the class as _deprecated_ and _internal-only_ to avoid unexpected reference.

Feel free to give it a shot and let me know if you have further question.

**Comment by joaoricardoboti** [comment]
The Enum class was added again, but the release `0.10.0` (the latest one) doesn't have the Enum. So, when install some dependency that uses this library, the source still outdated.
