### ISSUE TITLE
Pydantic support

### ISSUE THREAD

**Issue by jplock** [amazon-ion/ion-python#287]
I would like to serialize a Pydantic model into a base64-encoded Ion binary string to store in a binary DynamoDB attribute. It feels like a lot of round trips between Ion and a string JSON implementation to make this happen currently.

**Comment by cheqianh** [comment]
Hey jplock, we will look into your question and get back to you when have update.

**Comment by cheqianh** [comment]
Would you mind elaborating the use case a little bit more, where does `a lot of round trips` happened?

**Comment by jplock** [comment]
I'm going to close this PR. After doing some testing, using [model_dump](https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_dump) to dump to a Python dict (using `mode=python` to include Python objects) seems to work well with `simpleion.dumps()` (types are retained)
