### ISSUE TITLE
Convert IonPyDict to regular Python dict, so that it is compatible with dataframe library like pandas polars

### ISSUE THREAD

**Issue by MacHu-GWU** [amazon-ion/ion-python#362]
My company are using DynamoDB heavily and use DynamoDB export to convert a DynamoDB table into a bunch of parquet file. We want to parse the exported ion file and then convert it to polars dataframe. However, polars dataframe doesn't recognize IonPyDict.

**Comment by rmarrowstone** [comment]
As of version 0.12.0 you can control that using `IonPyValueModel.STRUCT_AS_STD_DICT`.

See https://github.com/amazon-ion/ion-python/blob/master/amazon/ion/simpleion.py#L208

For example:
```python
load(f, single_value=False, parse_eagerly=False,
                           value_model=IonPyValueModel.STRUCT_AS_STD_DICT)
```

Feel free to reopen if this doesn't meet your needs or somehow doesn't work for you.
