### ISSUE TITLE
Is it possible to use Enum from standard library instead of creating a custom class called Enum?

### ISSUE THREAD

**Issue by tokenmathguy** [amazon-ion/ion-python#54]
https://github.com/amzn/ion-python/blob/master/amazon/ion/util.py#L59

For python2.7 support, you can declare dependency on enum with Python license.

**Comment by rmarrowstone** [comment]
Just noticed this old issue. I actually addressed this a few months ago with: https://github.com/amazon-ion/ion-python/pull/221
