### ISSUE TITLE
boolean values not converted to the correct scalar type

### ISSUE THREAD

**Issue by hurdlea** [amazon-ion/ion-python#88]
In the Simpleion _load method the scalar evaluation of boolean values results in an integer being returned. This seems to the linked to the simple_types mapping of IonPyBool = IonPyInt and no patching to provide the correct type True | False based on the IonType.

In the _load reader loop the event correctly identifies the boolean value e.g.
```
_IonManagedThunkEvent(event_type=<IonEventType.SCALAR: 1>, ion_type=<IonType.BOOL: 1>, value=True, field_name=SymbolToken(text='key', sid=97, location=ImportLocation(name='namespace', position=88)), annotations=(), depth=4)
```
However, in the returned dict I get:
```
            "properties": {
                "key": 1
            }
```
Adding this to the _load event loop achieved the effect but it's not ideal.
```
    while event.event_type is not end_type:
        ion_type = event.ion_type
        if event.event_type is IonEventType.CONTAINER_START:
            container = _FROM_ION_TYPE[ion_type].from_event(event)
            _load(container, reader, IonEventType.CONTAINER_END, ion_type is IonType.STRUCT)
            add(container)
        elif event.event_type is IonEventType.SCALAR:
            if event.value is None or ion_type is IonType.NULL or event.ion_type.is_container:
                scalar = IonPyNull.from_event(event)
            elif ion_type is IonType.BOOL:
                scalar = event.value
            else:
                scalar = _FROM_ION_TYPE[ion_type].from_event(event)
            add(scalar)
        event = reader.send(NEXT_EVENT)
```

**Comment by almann** [comment]
My recollection of this (and it has been a long time), has to do with sub-typing `True` and `False`, which Python doesn't let you do (see [this thread][1]).  IIRC, we have this problem with `None` as well.

That said, a potential solution here is, in the non-annotated case (where the Boolean value has no additional Ion value type meta-data like annotations), we could potentially use the non-Ion type there.  I'd have to dig into this a bit deeper, to make sure this doesn't break anything, but I think it could work at the cost of a slight bit more complexity.

[1]: https://mail.python.org/pipermail/python-dev/2002-March/020822.html

**Comment by rmarrowstone** [comment]
A different user recently asked about this behavior and it prompted me to dig a bit. Here's what I found.

I don't believe that the type of the values in memory are incorrect. I do believe that the behavior is confusing for users, because the `__repr__` is confusing and the `type()` is misleading. 

Consider:
```
>>> b = simpleion.loads('true')
>>> b
1
>>> type(b)
<class 'amazon.ion.simple_types.IonPyInt'>
>>> b.ion_type
<IonType.BOOL: 1>
>>> simpleion.dumps(b, binary=False)
'$ion_1_0 true'
```

So we can see that simpleion does correctly roundtrip the value and that the `ion_type` is correct.

There is however a correctness issue with equality:
```
>>> from amazon.ion import simpleion
>>> i = simpleion.loads('1')
>>> b = simpleion.loads('true')
>>> i == b
True <--- whoops that's not right!!!
```
